//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunDau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeyWords { get; set; }
        public Nullable<int> Product { get; set; }
        public string Alias { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
